### ISSUE TITLE
(load ) command

### ISSUE THREAD

**Issue by ovenpasta** [fourthbit/spheres#11]
I have problems with the load command with spheres
If I need to load a file as follows

```
(load (string-append "/base/path/" "filename.scm"))
```

 I get the following error

```
*** ERROR -- load -- library or file required:  (string-append "/base/path/" "filename.scm")
```

Even if the file exists.

The plain (load) command of gambit (without spheres syntax)  behaves as expected.
Any suggestions?

**Comment by alvatar** [comment]
Ok, I see. The problem is that sphere's `load` is a macro that needs to detect if you are providing a library or a file. What do you think if I provide the support for what you want as:
`(load (lambda() <anything that produces a string or a library definition>))`

**Comment by alvatar** [comment]
Otherwise you can just do:
``(load ,(string-append "fo" "o"))`
and it will expand.

This would be very nice if it is documented...

**Comment by ovenpasta** [comment]
Ok.... but... what about compatibility with already written code? maybe better to name it load\* or something?
Thanks

**Comment by alvatar** [comment]
The reason is because you are not supposed to use normal load when you use spheres. However, if you really want the lower-level behavior, it is easy to make a function that works as `load`:

```
(define (default-load file) (##load file (lambda (_ __) #f) #t #t #f))
```

Compatibility with written code is not possible without these minor changes, and it is not intended to. There will be always changes that are necessary, but I would say that is expected in Scheme. Spheres however tries to make it easier to move to R7RS though.
Additionally, the load macro is to be used in the REPL and in interpreted code, otherwise you'll use Spheres' ssrun tasks. Using it in compiled code for dynamically loading vanilla Gambit code is still supported, through the low-level ##load. Otherwise I recommend converting your code into a library so it is loaded by spheres' load and you benefit of the namespace protection.
